[package]
name = "day1"
version = "0.1.0"
authors = ["miroesli <17695280+miroesli@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
